name: deploy dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::959710271722:role/GithubActionsRole
        role-session-name: GithubActionsSession

    - name: npm ci
      run: npm ci

    - name: deploy to dev
      run: npx sls deploy

    # - name: integration tests
    #   run: npm run test:int

    # - name: e2e tests
    #   run: npm run test:e2e

    # - name: integration tests
    #   run: |
    #     npm run sls -- export-env -s dev -i
    #     npm run integration-test

    # - name: e2e tests
    #   run: |
    #     npm run sls -- export-env -s dev
    #     npm run e2e-test

    # - name: notify slack
    # - name: Report Status
    #   if: always()
    #   uses: ravsamhq/notify-slack-action@v1
    #   with:
    #     status: ${{ job.status }}
    #     notify_when: 'failure'
    #     notification_title: '{workflow} has {status_message}'
    #     message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
    #     footer: 'Linked to Repo <{repo_url}|{repo}>'
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}         # or a specific color like 'good' or '#ff00ff'
